type Query {
    # Measure
    getMeasureById(id: ID!): Measure
    getAllMeasures: [Measure]
    getMeasuresByThingId(thingId: String!): GetMeasuresByThingIdResponse
}

# ///////////////////////////// MUTATIONS /////////////////////////

type Mutation {
    #Measure
    saveMeasure(measureInput: MeasureInput!): SaveMeasureResponse
    deleteMeasureById(measureId: ID!): DeleteResponse
    deleteAllMeasures: DeleteResponse
}

# ///////////////////////////// INPUTS /////////////////////////
input MeasureInput {
    thingId: String
    meteo: MeteoInput
    battery: BatteryInput
}

input MeteoInput {
    temperature: Float
    humidityRate: Float
    airPressure: Int
}

input BatteryInput {
    batteryState: Int
    outputVoltage: Float
}

# ///////////////////////////// RESPONSES /////////////////////////

type SaveMeasureResponse {
    success: Boolean
    message: String
    measure: Measure
}

type GetMeasuresByThingIdResponse{
    success: Boolean
    message: String
    measures: [Measure]
}

type DeleteResponse {
    success: Boolean
    message: String
}

# ///////////////////////////// TYPE ENTITIES /////////////////////////

type Measure {
    id: ID
    thingId: String
    timestamp: String
    meteo: Meteo
    battery: Battery
}

type Meteo {
    temperature: Float
    humidityRate: Float
    airPressure: Float
}

type Battery {
    batteryState: Int
    outputVoltage: Float
}


