spring.application.name=MeteoDatas-SpringApp
spring.config.import=.env.properties

# GraphQL
spring.graphql.graphiql.enabled=true

#JPA/Hibernate configuration
#spring.jpa.hibernate.ddl-auto=create-drop
#spring.jpa.show-sql=true
#spring.jpa.properties.hibernate.format_sql=true

# MongoDB Database configuration (mongodb)
spring.mongodb.host=mongodb
spring.mongodb.port=27017
spring.mongodb.database=${MONGODB_DATABASE}
spring.mongodb.username=${MONGODB_USERNAME}
spring.mongodb.password=${MONGODB_PASSWORD}
spring.mongodb.uri=mongodb://${MONGODB_USERNAME}:${MONGODB_PASSWORD}@${MONGODB_URL}:27017/${MONGODB_DATABASE}?authSource=admin

# milliseconds
#app.expiration-time=2700000

# Front-URL
#spring.front-url=${FRONT_URL}
